//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcConsumer.CalcService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexNumber", Namespace="http://schemas.datacontract.org/2004/07/WCFIntro")]
    [System.SerializableAttribute()]
    public partial class ComplexNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ImagPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RealPartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImagPart {
            get {
                return this.ImagPartField;
            }
            set {
                if ((this.ImagPartField.Equals(value) != true)) {
                    this.ImagPartField = value;
                    this.RaisePropertyChanged("ImagPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RealPart {
            get {
                return this.RealPartField;
            }
            set {
                if ((this.RealPartField.Equals(value) != true)) {
                    this.RealPartField = value;
                    this.RaisePropertyChanged("RealPart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalcService.ICalcService")]
    public interface ICalcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CreateComplexNumber", ReplyAction="http://tempuri.org/ICalcService/CreateComplexNumberResponse")]
        CalcConsumer.CalcService.ComplexNumber CreateComplexNumber(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/CreateComplexNumber", ReplyAction="http://tempuri.org/ICalcService/CreateComplexNumberResponse")]
        System.Threading.Tasks.Task<CalcConsumer.CalcService.ComplexNumber> CreateComplexNumberAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetData", ReplyAction="http://tempuri.org/ICalcService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetData", ReplyAction="http://tempuri.org/ICalcService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetRealPart", ReplyAction="http://tempuri.org/ICalcService/GetRealPartResponse")]
        int GetRealPart(CalcConsumer.CalcService.ComplexNumber complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetRealPart", ReplyAction="http://tempuri.org/ICalcService/GetRealPartResponse")]
        System.Threading.Tasks.Task<int> GetRealPartAsync(CalcConsumer.CalcService.ComplexNumber complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetImagPart", ReplyAction="http://tempuri.org/ICalcService/GetImagPartResponse")]
        int GetImagPart(CalcConsumer.CalcService.ComplexNumber complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalcService/GetImagPart", ReplyAction="http://tempuri.org/ICalcService/GetImagPartResponse")]
        System.Threading.Tasks.Task<int> GetImagPartAsync(CalcConsumer.CalcService.ComplexNumber complex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalcServiceChannel : CalcConsumer.CalcService.ICalcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcServiceClient : System.ServiceModel.ClientBase<CalcConsumer.CalcService.ICalcService>, CalcConsumer.CalcService.ICalcService {
        
        public CalcServiceClient() {
        }
        
        public CalcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CalcConsumer.CalcService.ComplexNumber CreateComplexNumber(int a, int b) {
            return base.Channel.CreateComplexNumber(a, b);
        }
        
        public System.Threading.Tasks.Task<CalcConsumer.CalcService.ComplexNumber> CreateComplexNumberAsync(int a, int b) {
            return base.Channel.CreateComplexNumberAsync(a, b);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public int GetRealPart(CalcConsumer.CalcService.ComplexNumber complex) {
            return base.Channel.GetRealPart(complex);
        }
        
        public System.Threading.Tasks.Task<int> GetRealPartAsync(CalcConsumer.CalcService.ComplexNumber complex) {
            return base.Channel.GetRealPartAsync(complex);
        }
        
        public int GetImagPart(CalcConsumer.CalcService.ComplexNumber complex) {
            return base.Channel.GetImagPart(complex);
        }
        
        public System.Threading.Tasks.Task<int> GetImagPartAsync(CalcConsumer.CalcService.ComplexNumber complex) {
            return base.Channel.GetImagPartAsync(complex);
        }
    }
}
